version: 1.0.{build}

image:
  - Visual Studio 2022
  - Ubuntu2004

platform:
  - x64

environment:
  matrix:
    - nodejs_version: "22"
    - nodejs_version: "20"
    - nodejs_version: "18"
    - nodejs_version: "16"

test_script:
  - ps: Write-Host "jspurefix test script"    

for:
-
    matrix:
      only:
        - image: Visual Studio 2022
  
    clone_folder: c:\projects\jspurefix
    install:
      - ps: Install-Product node $env:nodejs_version $env:platform
      - npm install
    build_script:
      - node --version
      - cmd: script\build.cmd
    test_script:
      - cmd: script\test.cmd
-        
    matrix:
      only:
        - image: Ubuntu2004
        - platform: x64
    clone_folder: /home/appveyor/projects/jspurefix 
    
    install:
      - nvm install $nodejs_version
      - npm install

    build_script:
      - node --version
      - sh: script/build.sh

    test_script:
      - sh: "npm run repo44-bench-er"
      - sh: "npm run tcp-tc"
      - sh: "npm run http-oms"
      - sh: "npm run tcp-qf-md"
      - sh: "npm run tcp-rec-sk"
      - sh: "npm test"

