import { IInstrumentLegNoLegSecurityAltID } from './instrument_leg_no_leg_security_alt_id'

export interface IInstrumentLeg {
  LegSymbol?: string// [1] 600 (String)
  LegSymbolSfx?: string// [2] 601 (String)
  LegSecurityID?: string// [3] 602 (String)
  LegSecurityIDSource?: string// [4] 603 (String)
  NoLegSecurityAltID?: IInstrumentLegNoLegSecurityAltID[]// [5] LegSecurityAltID.605, LegSecurityAltIDSource.606
  LegProduct?: number// [6] 607 (Int)
  LegCFICode?: string// [7] 608 (String)
  LegSecurityType?: string// [8] 609 (String)
  LegMaturityMonthYear?: string// [9] 610 (String)
  LegMaturityDate?: Date// [10] 611 (LocalDate)
  LegCouponPaymentDate?: string// [11] 248 (String)
  LegIssueDate?: string// [12] 249 (String)
  LegRepoCollateralSecurityType?: string// [13] 250 (String)
  LegRepurchaseTerm?: number// [14] 251 (Int)
  LegRepurchaseRate?: number// [15] 252 (Float)
  LegFactor?: number// [16] 253 (Float)
  LegCreditRating?: string// [17] 257 (String)
  LegInstrRegistry?: string// [18] 599 (String)
  LegCountryOfIssue?: string// [19] 596 (String)
  LegStateOrProvinceOfIssue?: string// [20] 597 (String)
  LegLocaleOfIssue?: string// [21] 598 (String)
  LegRedemptionDate?: string// [22] 254 (String)
  LegStrikePrice?: number// [23] 612 (Float)
  LegOptAttribute?: string// [24] 613 (String)
  LegContractMultiplier?: number// [25] 614 (Float)
  LegCouponRate?: number// [26] 615 (Float)
  LegSecurityExchange?: string// [27] 616 (String)
  LegIssuer?: string// [28] 617 (String)
  EncodedLegIssuerLen?: number// [29] 618 (Length)
  EncodedLegIssuer?: Buffer// [30] 619 (RawData)
  LegSecurityDesc?: string// [31] 620 (String)
  EncodedLegSecurityDescLen?: number// [32] 621 (Length)
  EncodedLegSecurityDesc?: Buffer// [33] 622 (RawData)
  LegRatioQty?: number// [34] 623 (Float)
  LegSide?: string// [35] 624 (String)
}
