import { IUnderlyingInstrumentNoUnderlyingSecurityAltID } from './underlying_instrument_no_underlying_security_alt_id'

export interface IUnderlyingInstrument {
  UnderlyingSymbol?: string// [1] 311 (String)
  UnderlyingSymbolSfx?: string// [2] 312 (String)
  UnderlyingSecurityID?: string// [3] 309 (String)
  UnderlyingSecurityIDSource?: string// [4] 305 (String)
  NoUnderlyingSecurityAltID?: IUnderlyingInstrumentNoUnderlyingSecurityAltID[]// [5] UnderlyingSecurityAltID.458, UnderlyingSecurityAltIDSource.459
  UnderlyingProduct?: number// [6] 462 (Int)
  UnderlyingCFICode?: string// [7] 463 (String)
  UnderlyingSecurityType?: string// [8] 310 (String)
  UnderlyingMaturityMonthYear?: string// [9] 313 (String)
  UnderlyingMaturityDate?: Date// [10] 542 (LocalDate)
  UnderlyingPutOrCall?: number// [11] 315 (Int)
  UnderlyingCouponPaymentDate?: string// [12] 241 (String)
  UnderlyingIssueDate?: string// [13] 242 (String)
  UnderlyingRepoCollateralSecurityType?: string// [14] 243 (String)
  UnderlyingRepurchaseTerm?: number// [15] 244 (Int)
  UnderlyingRepurchaseRate?: number// [16] 245 (Float)
  UnderlyingFactor?: number// [17] 246 (Float)
  UnderlyingCreditRating?: string// [18] 256 (String)
  UnderlyingInstrRegistry?: string// [19] 595 (String)
  UnderlyingCountryOfIssue?: string// [20] 592 (String)
  UnderlyingStateOrProvinceOfIssue?: string// [21] 593 (String)
  UnderlyingLocaleOfIssue?: string// [22] 594 (String)
  UnderlyingRedemptionDate?: string// [23] 247 (String)
  UnderlyingStrikePrice?: number// [24] 316 (Float)
  UnderlyingOptAttribute?: string// [25] 317 (String)
  UnderlyingContractMultiplier?: number// [26] 436 (Float)
  UnderlyingCouponRate?: number// [27] 435 (Float)
  UnderlyingSecurityExchange?: string// [28] 308 (String)
  UnderlyingIssuer?: string// [29] 306 (String)
  EncodedUnderlyingIssuerLen?: number// [30] 362 (Length)
  EncodedUnderlyingIssuer?: Buffer// [31] 363 (RawData)
  UnderlyingSecurityDesc?: string// [32] 307 (String)
  EncodedUnderlyingSecurityDescLen?: number// [33] 364 (Length)
  EncodedUnderlyingSecurityDesc?: Buffer// [34] 365 (RawData)
}
