import { IStandardHeader } from './set/standard_header'
import { IApplIDRequestGrp } from './set/appl_id_request_grp'
import { IStandardTrailer } from './set/standard_trailer'
import { IParties } from './set/parties'

/*
****************************************************************
* This message is used to request a retransmission of a set of *
* one or more messages generated by the application specified  *
* in RefApplID (1355).                                         *
****************************************************************
*/
export interface IApplicationMessageRequest {
  StandardHeader: IStandardHeader// [1] BeginString.8, BodyLength.9 .. HopRefID.630
  ApplReqID: string// [2] 1346 (String)
  ApplReqType: number// [3] 1347 (Int)
  ApplIDRequestGrp?: IApplIDRequestGrp[]// [4] RefApplID.1355, ApplBegSeqNum.1182 .. RefApplReqID.1433
  Text?: string// [5] 58 (String)
  EncodedTextLen?: number// [6] 354 (Int)
  EncodedText?: Buffer// [7] 355 (RawData)
  StandardTrailer: IStandardTrailer// [8] SignatureLength.93, Signature.89, CheckSum.10
  Parties?: IParties[]// [9] PartyID.448, PartyIDSource.447 .. PartySubIDType.803
}
