export interface IAdditionalTermBondRefGrpNoAdditionalTermBondRefs {
  AdditionalTermBondSecurityID?: string// [1] 40001 (String)
  AdditionalTermBondSecurityIDSource?: string// [2] 40002 (String)
  AdditionalTermBondDesc?: string// [3] 40003 (String)
  EncodedAdditionalTermBondDescLen?: number// [4] 40004 (Length)
  EncodedAdditionalTermBondDesc?: Buffer// [5] 40005 (RawData)
  AdditionalTermBondCurrency?: string// [6] 40006 (String)
  AdditionalTermBondIssuer?: string// [7] 40007 (String)
  EncodedAdditionalTermBondIssuerLen?: number// [8] 40008 (Length)
  EncodedAdditionalTermBondIssuer?: Buffer// [9] 40009 (RawData)
  AdditionalTermBondSeniority?: string// [10] 40010 (String)
  AdditionalTermBondCouponType?: number// [11] 40011 (Int)
  AdditionalTermBondCouponRate?: number// [12] 40012 (Float)
  AdditionalTermBondMaturityDate?: Date// [13] 40013 (LocalDate)
  AdditionalTermBondParValue?: number// [14] 40014 (Float)
  AdditionalTermBondCurrentTotalIssuedAmount?: number// [15] 40015 (Float)
  AdditionalTermBondCouponFrequencyPeriod?: number// [16] 40016 (Int)
  AdditionalTermBondCouponFrequencyUnit?: string// [17] 40017 (String)
  AdditionalTermBondDayCount?: number// [18] 40018 (Int)
}
