import { IComplexEventCreditEventQualifierGrpNoComplexEventCreditEventQualifiers } from './complex_event_credit_event_qualifier_grp_no_complex_event_credit_event_qualifiers'

export interface IComplexEventCreditEventQualifierGrp {
  NoComplexEventCreditEventQualifiers?: IComplexEventCreditEventQualifierGrpNoComplexEventCreditEventQualifiers[]// [1] ComplexEventCreditEventQualifier.41006
}
