import { IComplexEventAveragingObservationGrpNoComplexEventAveragingObservations } from './complex_event_averaging_observation_grp_no_complex_event_averaging_observations'

export interface IComplexEventAveragingObservationGrp {
  NoComplexEventAveragingObservations?: IComplexEventAveragingObservationGrpNoComplexEventAveragingObservations[]// [1] ComplexEventAveragingObservationNumber.40995, ComplexEventAveragingWeight.40996
}
