import { IDerivativeInstrumentPartySubIDsGrpNoDerivativeInstrumentPartySubIDs } from './derivative_instrument_party_sub_i_ds_grp_no_derivative_instrument_party_sub_i_ds'

export interface IDerivativeInstrumentPartySubIDsGrp {
  NoDerivativeInstrumentPartySubIDs?: IDerivativeInstrumentPartySubIDsGrpNoDerivativeInstrumentPartySubIDs[]// [1] DerivativeInstrumentPartySubID.1297, DerivativeInstrumentPartySubIDType.1298
}
