import { ILegPricingDateBusinessCenterGrpNoLegPricingDateBusinessCenters } from './leg_pricing_date_business_center_grp_no_leg_pricing_date_business_centers'

export interface ILegPricingDateBusinessCenterGrp {
  NoLegPricingDateBusinessCenters?: ILegPricingDateBusinessCenterGrpNoLegPricingDateBusinessCenters[]// [1] LegPricingDateBusinessCenter.41608
}
