export interface ILegPaymentStreamResetDates {
  LegPaymentStreamResetDateRelativeTo?: number// [1] 40303 (Int)
  LegPaymentStreamResetDateBusinessDayConvention?: number// [2] 40304 (Int)
  LegPaymentStreamResetFrequencyPeriod?: number// [3] 40306 (Int)
  LegPaymentStreamResetFrequencyUnit?: string// [4] 40307 (String)
  LegPaymentStreamResetWeeklyRollConvention?: string// [5] 40308 (String)
  LegPaymentStreamInitialFixingDateRelativeTo?: number// [6] 40309 (Int)
  LegPaymentStreamInitialFixingDateBusinessDayConvention?: number// [7] 40310 (Int)
  LegPaymentStreamInitialFixingDateOffsetPeriod?: number// [8] 40312 (Int)
  LegPaymentStreamInitialFixingDateOffsetUnit?: string// [9] 40313 (String)
  LegPaymentStreamInitialFixingDateOffsetDayType?: number// [10] 40314 (Int)
  LegPaymentStreamInitialFixingDateAdjusted?: Date// [11] 40315 (LocalDate)
  LegPaymentStreamFixingDateRelativeTo?: number// [12] 40316 (Int)
  LegPaymentStreamFixingDateBusinessDayConvention?: number// [13] 40317 (Int)
  LegPaymentStreamFixingDateOffsetPeriod?: number// [14] 40319 (Int)
  LegPaymentStreamFixingDateOffsetUnit?: string// [15] 40320 (String)
  LegPaymentStreamFixingDateOffsetDayType?: number// [16] 40321 (Int)
  LegPaymentStreamFixingDateAdjusted?: Date// [17] 40322 (LocalDate)
  LegPaymentStreamRateCutoffDateOffsetPeriod?: number// [18] 40323 (Int)
  LegPaymentStreamRateCutoffDateOffsetUnit?: string// [19] 40324 (String)
  LegPaymentStreamRateCutoffDateOffsetDayType?: number// [20] 40325 (Int)
}
