import { ILegPaymentStreamResetDateBusinessCenterGrpNoLegPaymentStreamResetDateBusinessCenters } from './leg_payment_stream_reset_date_business_center_grp_no_leg_payment_stream_reset_date_business_centers'

export interface ILegPaymentStreamResetDateBusinessCenterGrp {
  NoLegPaymentStreamResetDateBusinessCenters?: ILegPaymentStreamResetDateBusinessCenterGrpNoLegPaymentStreamResetDateBusinessCenters[]// [1] LegPaymentStreamResetDateBusinessCenter.40305
}
