import { ILegPaymentStreamNonDeliverableFixingDatesBusinessCenterGrpNoLegPaymentStreamNonDeliverableFixingDateBusinessCenters } from './leg_payment_stream_non_deliverable_fixing_dates_business_center_grp_no_leg_payment_stream_non_deliverable_fixing_date_business_centers'

export interface ILegPaymentStreamNonDeliverableFixingDatesBusinessCenterGrp {
  NoLegPaymentStreamNonDeliverableFixingDateBusinessCenters?: ILegPaymentStreamNonDeliverableFixingDatesBusinessCenterGrpNoLegPaymentStreamNonDeliverableFixingDateBusinessCenters[]// [1] LegPaymentStreamNonDeliverableFixingDatesBusinessCenter.40361
}
