import { ILegProvisionOptionExerciseBusinessCenterGrpNoLegProvisionOptionExerciseBusinessCenters } from './leg_provision_option_exercise_business_center_grp_no_leg_provision_option_exercise_business_centers'

export interface ILegProvisionOptionExerciseBusinessCenterGrp {
  NoLegProvisionOptionExerciseBusinessCenters?: ILegProvisionOptionExerciseBusinessCenterGrpNoLegProvisionOptionExerciseBusinessCenters[]// [1] LegProvisionOptionExerciseBusinessCenter.40477
}
