import { ILegStreamFirstPeriodStartDateBusinessCenterGrpNoLegStreamFirstPeriodStartDateBusinessCenters } from './leg_stream_first_period_start_date_business_center_grp_no_leg_stream_first_period_start_date_business_centers'

export interface ILegStreamFirstPeriodStartDateBusinessCenterGrp {
  NoLegStreamFirstPeriodStartDateBusinessCenters?: ILegStreamFirstPeriodStartDateBusinessCenterGrpNoLegStreamFirstPeriodStartDateBusinessCenters[]// [1] LegStreamFirstPeriodStartDateBusinessCenter.40269
}
