import { ILegPaymentScheduleFixingDateBusinessCenterGrpNoLegPaymentScheduleFixingDateBusinessCenters } from './leg_payment_schedule_fixing_date_business_center_grp_no_leg_payment_schedule_fixing_date_business_centers'

export interface ILegPaymentScheduleFixingDateBusinessCenterGrp {
  NoLegPaymentScheduleFixingDateBusinessCenters?: ILegPaymentScheduleFixingDateBusinessCenterGrpNoLegPaymentScheduleFixingDateBusinessCenters[]// [1] LegPaymentScheduleFixingDateBusinessCenter.40400
}
