import { ILegDividendPeriodBusinessCenterGrpNoLegDividendPeriodBusinessCenters } from './leg_dividend_period_business_center_grp_no_leg_dividend_period_business_centers'

export interface ILegDividendPeriodBusinessCenterGrp {
  NoLegDividendPeriodBusinessCenters?: ILegDividendPeriodBusinessCenterGrpNoLegDividendPeriodBusinessCenters[]// [1] LegDividendPeriodBusinessCenter.42387
}
