import { ILegComplexEventAveragingObservationGrpNoLegComplexEventAveragingObservations } from './leg_complex_event_averaging_observation_grp_no_leg_complex_event_averaging_observations'

export interface ILegComplexEventAveragingObservationGrp {
  NoLegComplexEventAveragingObservations?: ILegComplexEventAveragingObservationGrpNoLegComplexEventAveragingObservations[]// [1] LegComplexEventAveragingObservationNumber.41364, LegComplexEventAveragingWeight.41365
}
