export interface ILegProvisionOptionRelevantUnderlyingDateBusinessCenterGrpNoLegProvisionOptionRelevantUnderlyingDateBusinessCenters {
  LegProvisionOptionRelevantUnderlyingDateBusinessCenter?: string// [1] 40510 (String)
}
