import { ILegStreamCommoditySettlTimeGrpNoLegStreamCommoditySettlTimes } from './leg_stream_commodity_settl_time_grp_no_leg_stream_commodity_settl_times'

export interface ILegStreamCommoditySettlTimeGrp {
  NoLegStreamCommoditySettlTimes?: ILegStreamCommoditySettlTimeGrpNoLegStreamCommoditySettlTimes[]// [1] LegStreamCommoditySettlStart.41684, LegStreamCommoditySettlEnd.41685, LegStreamCommoditySettlTimeType.41935
}
