export interface ILegReturnRateDateGrpNoLegReturnRateDates {
  LegReturnRateDateMode?: number// [1] 42509 (Int)
  LegReturnRateValuationDateRelativeTo?: number// [2] 42510 (Int)
  LegReturnRateValuationDateOffsetPeriod?: number// [3] 42511 (Int)
  LegReturnRateValuationDateOffsetUnit?: string// [4] 42512 (String)
  LegReturnRateValuationDateOffsetDayType?: number// [5] 42513 (Int)
  LegReturnRateValuationStartDateUnadjusted?: Date// [6] 42514 (LocalDate)
  LegReturnRateValuationStartDateRelativeTo?: number// [7] 42515 (Int)
  LegReturnRateValuationStartDateOffsetPeriod?: number// [8] 42516 (Int)
  LegReturnRateValuationStartDateOffsetUnit?: string// [9] 42517 (String)
  LegReturnRateValuationStartDateOffsetDayType?: number// [10] 42518 (Int)
  LegReturnRateValuationStartDateAdjusted?: Date// [11] 42519 (LocalDate)
  LegReturnRateValuationEndDateUnadjusted?: Date// [12] 42520 (LocalDate)
  LegReturnRateValuationEndDateRelativeTo?: number// [13] 42521 (Int)
  LegReturnRateValuationEndDateOffsetPeriod?: number// [14] 42522 (Int)
  LegReturnRateValuationEndDateOffsetUnit?: string// [15] 42523 (String)
  LegReturnRateValuationEndDateOffsetDayType?: number// [16] 42524 (Int)
  LegReturnRateValuationEndDateAdjusted?: Date// [17] 42525 (LocalDate)
  LegReturnRateValuationFrequencyPeriod?: number// [18] 42526 (Int)
  LegReturnRateValuationFrequencyUnit?: string// [19] 42527 (String)
  LegReturnRateValuationFrequencyRollConvention?: string// [20] 42528 (String)
  LegReturnRateValuationDateBusinessDayConvention?: number// [21] 42529 (Int)
}
