import { ILegPaymentScheduleRateSourceGrpNoLegPaymentScheduleRateSources } from './leg_payment_schedule_rate_source_grp_no_leg_payment_schedule_rate_sources'

export interface ILegPaymentScheduleRateSourceGrp {
  NoLegPaymentScheduleRateSources?: ILegPaymentScheduleRateSourceGrpNoLegPaymentScheduleRateSources[]// [1] LegPaymentScheduleRateSource.40415, LegPaymentScheduleRateSourceType.40416, LegPaymentScheduleReferencePage.40417
}
