import { ILegOptionExerciseExpirationDateBusinessCenterGrpNoLegOptionExerciseExpirationDateBusinessCenters } from './leg_option_exercise_expiration_date_business_center_grp_no_leg_option_exercise_expiration_date_business_centers'

export interface ILegOptionExerciseExpirationDateBusinessCenterGrp {
  NoLegOptionExerciseExpirationDateBusinessCenters?: ILegOptionExerciseExpirationDateBusinessCenterGrpNoLegOptionExerciseExpirationDateBusinessCenters[]// [1] LegOptionExerciseExpirationDateBusinessCenter.41516
}
