import { ILegPaymentScheduleInterimExchangeDateBusinessCenterGrpNoLegPaymentScheduleInterimExchangeDateBusinessCenters } from './leg_payment_schedule_interim_exchange_date_business_center_grp_no_leg_payment_schedule_interim_exchange_date_business_centers'

export interface ILegPaymentScheduleInterimExchangeDateBusinessCenterGrp {
  NoLegPaymentScheduleInterimExchangeDateBusinessCenters?: ILegPaymentScheduleInterimExchangeDateBusinessCenterGrpNoLegPaymentScheduleInterimExchangeDateBusinessCenters[]// [1] LegPaymentScheduleInterimExchangeDatesBusinessCenter.40409
}
