import { ILegProvisionCashSettlPaymentDateBusinessCenterGrpNoLegProvisionCashSettlPaymentDateBusinessCenters } from './leg_provision_cash_settl_payment_date_business_center_grp_no_leg_provision_cash_settl_payment_date_business_centers'

export interface ILegProvisionCashSettlPaymentDateBusinessCenterGrp {
  NoLegProvisionCashSettlPaymentDateBusinessCenters?: ILegProvisionCashSettlPaymentDateBusinessCenterGrpNoLegProvisionCashSettlPaymentDateBusinessCenters[]// [1] LegProvisionCashSettlPaymentDateBusinessCenter.40517
}
