import { ILegProvisionOptionExpirationDateBusinessCenterGrpNoLegProvisionOptionExpirationDateBusinessCenters } from './leg_provision_option_expiration_date_business_center_grp_no_leg_provision_option_expiration_date_business_centers'

export interface ILegProvisionOptionExpirationDateBusinessCenterGrp {
  NoLegProvisionOptionExpirationDateBusinessCenters?: ILegProvisionOptionExpirationDateBusinessCenterGrpNoLegProvisionOptionExpirationDateBusinessCenters[]// [1] LegProvisionOptionExpirationDateBusinessCenter.40500
}
