import { ILegFinancingContractualDefinitionsGrpNoLegContractualDefinitions } from './leg_financing_contractual_definitions_grp_no_leg_contractual_definitions'

export interface ILegFinancingContractualDefinitionsGrp {
  NoLegContractualDefinitions?: ILegFinancingContractualDefinitionsGrpNoLegContractualDefinitions[]// [1] LegContractualDefinition.42199
}
