import { ILegDividendAccrualPaymentDateBusinessCenterGrpNoLegDividendAccrualPaymentDateBusinessCenters } from './leg_dividend_accrual_payment_date_business_center_grp_no_leg_dividend_accrual_payment_date_business_centers'

export interface ILegDividendAccrualPaymentDateBusinessCenterGrp {
  NoLegDividendAccrualPaymentDateBusinessCenters?: ILegDividendAccrualPaymentDateBusinessCenterGrpNoLegDividendAccrualPaymentDateBusinessCenters[]// [1] LegDividendAccrualPaymentDateBusinessCenter.42311
}
