import { ILegComplexEventPeriodDateGrpNoLegComplexEventPeriodDateTimes } from './leg_complex_event_period_date_grp_no_leg_complex_event_period_date_times'

export interface ILegComplexEventPeriodDateGrp {
  NoLegComplexEventPeriodDateTimes?: ILegComplexEventPeriodDateGrpNoLegComplexEventPeriodDateTimes[]// [1] LegComplexEventPeriodDate.41377, LegComplexEventPeriodTime.41378
}
