import { ILegComplexEventDateBusinessCenterGrpNoLegComplexEventDateBusinessCenters } from './leg_complex_event_date_business_center_grp_no_leg_complex_event_date_business_centers'

export interface ILegComplexEventDateBusinessCenterGrp {
  NoLegComplexEventDateBusinessCenters?: ILegComplexEventDateBusinessCenterGrpNoLegComplexEventDateBusinessCenters[]// [1] LegComplexEventDateBusinessCenter.41388
}
