import { ILegPaymentStreamPricingBusinessCenterGrpNoLegPaymentStreamPricingBusinessCenters } from './leg_payment_stream_pricing_business_center_grp_no_leg_payment_stream_pricing_business_centers'

export interface ILegPaymentStreamPricingBusinessCenterGrp {
  NoLegPaymentStreamPricingBusinessCenters?: ILegPaymentStreamPricingBusinessCenterGrpNoLegPaymentStreamPricingBusinessCenters[]// [1] LegPaymentStreamPricingBusinessCenter.41562
}
