import { ILegProvisionOptionRelevantUnderlyingDateBusinessCenterGrpNoLegProvisionOptionRelevantUnderlyingDateBusinessCenters } from './leg_provision_option_relevant_underlying_date_business_center_grp_no_leg_provision_option_relevant_underlying_date_business_centers'

export interface ILegProvisionOptionRelevantUnderlyingDateBusinessCenterGrp {
  NoLegProvisionOptionRelevantUnderlyingDateBusinessCenters?: ILegProvisionOptionRelevantUnderlyingDateBusinessCenterGrpNoLegProvisionOptionRelevantUnderlyingDateBusinessCenters[]// [1] LegProvisionOptionRelevantUnderlyingDateBusinessCenter.40510
}
