import { ILegPhysicalSettlDeliverableObligationGrpNoLegPhysicalSettlDeliverableObligations } from './leg_physical_settl_deliverable_obligation_grp_no_leg_physical_settl_deliverable_obligations'

export interface ILegPhysicalSettlDeliverableObligationGrp {
  NoLegPhysicalSettlDeliverableObligations?: ILegPhysicalSettlDeliverableObligationGrpNoLegPhysicalSettlDeliverableObligations[]// [1] LegPhysicalSettlDeliverableObligationType.41605, LegPhysicalSettlDeliverableObligationValue.41606
}
