import { ILegPaymentStreamPricingDayGrpNoLegPaymentStreamPricingDays } from './leg_payment_stream_pricing_day_grp_no_leg_payment_stream_pricing_days'

export interface ILegPaymentStreamPricingDayGrp {
  NoLegPaymentStreamPricingDays?: ILegPaymentStreamPricingDayGrpNoLegPaymentStreamPricingDays[]// [1] LegPaymentStreamPricingDayOfWeek.41597, LegPaymentStreamPricingDayNumber.41598
}
