import { ILegPaymentStreamCompoundingDatesBusinessCenterGrpNoLegPaymentStreamCompoundingDatesBusinessCenters } from './leg_payment_stream_compounding_dates_business_center_grp_no_leg_payment_stream_compounding_dates_business_centers'

export interface ILegPaymentStreamCompoundingDatesBusinessCenterGrp {
  NoLegPaymentStreamCompoundingDatesBusinessCenters?: ILegPaymentStreamCompoundingDatesBusinessCenterGrpNoLegPaymentStreamCompoundingDatesBusinessCenters[]// [1] LegPaymentStreamCompoundingDatesBusinessCenter.42420
}
