export interface ILegAdditionalTermBondRefGrpNoLegAdditionalTermBondRefs {
  LegAdditionalTermBondSecurityID?: string// [1] 41317 (String)
  LegAdditionalTermBondSecurityIDSource?: string// [2] 41318 (String)
  LegAdditionalTermBondDesc?: string// [3] 41319 (String)
  EncodedLegAdditionalTermBondDescLen?: number// [4] 41320 (Length)
  EncodedLegAdditionalTermBondDesc?: Buffer// [5] 41321 (RawData)
  LegAdditionalTermBondCurrency?: string// [6] 41322 (String)
  LegAdditionalTermBondIssuer?: string// [7] 41323 (String)
  EncodedLegAdditionalTermBondIssuerLen?: number// [8] 41324 (Length)
  EncodedLegAdditionalTermBondIssuer?: Buffer// [9] 41325 (RawData)
  LegAdditionalTermBondSeniority?: string// [10] 41326 (String)
  LegAdditionalTermBondCouponType?: number// [11] 41327 (Int)
  LegAdditionalTermBondCouponRate?: number// [12] 41328 (Float)
  LegAdditionalTermBondMaturityDate?: Date// [13] 41329 (LocalDate)
  LegAdditionalTermBondParValue?: number// [14] 41330 (Float)
  LegAdditionalTermBondCurrentTotalIssuedAmount?: number// [15] 41331 (Float)
  LegAdditionalTermBondCouponFrequencyPeriod?: number// [16] 41332 (Int)
  LegAdditionalTermBondCouponFrequencyUnit?: string// [17] 41333 (String)
  LegAdditionalTermBondDayCount?: number// [18] 41334 (Int)
}
