import { ILegPaymentStreamInitialFixingDateBusinessCenterGrpNoLegPaymentStreamInitialFixingDateBusinessCenters } from './leg_payment_stream_initial_fixing_date_business_center_grp_no_leg_payment_stream_initial_fixing_date_business_centers'

export interface ILegPaymentStreamInitialFixingDateBusinessCenterGrp {
  NoLegPaymentStreamInitialFixingDateBusinessCenters?: ILegPaymentStreamInitialFixingDateBusinessCenterGrpNoLegPaymentStreamInitialFixingDateBusinessCenters[]// [1] LegPaymentStreamInitialFixingDateBusinessCenter.40311
}
