import { ILegStreamCommoditySettlBusinessCenterGrpNoLegStreamCommoditySettlBusinessCenters } from './leg_stream_commodity_settl_business_center_grp_no_leg_stream_commodity_settl_business_centers'

export interface ILegStreamCommoditySettlBusinessCenterGrp {
  NoLegStreamCommoditySettlBusinessCenters?: ILegStreamCommoditySettlBusinessCenterGrpNoLegStreamCommoditySettlBusinessCenters[]// [1] LegStreamCommoditySettlBusinessCenter.41647
}
