import { ILegSettlMethodElectionDateBusinessCenterGrpNoLegSettlMethodElectionDateBusinessCenters } from './leg_settl_method_election_date_business_center_grp_no_leg_settl_method_election_date_business_centers'

export interface ILegSettlMethodElectionDateBusinessCenterGrp {
  NoLegSettlMethodElectionDateBusinessCenters?: ILegSettlMethodElectionDateBusinessCenterGrpNoLegSettlMethodElectionDateBusinessCenters[]// [1] LegSettlMethodElectionDateBusinessCenter.42582
}
