import { ILegReturnRateValuationDateBusinessCenterGrpNoLegReturnRateValuationDateBusinessCenters } from './leg_return_rate_valuation_date_business_center_grp_no_leg_return_rate_valuation_date_business_centers'

export interface ILegReturnRateValuationDateBusinessCenterGrp {
  NoLegReturnRateValuationDateBusinessCenters?: ILegReturnRateValuationDateBusinessCenterGrpNoLegReturnRateValuationDateBusinessCenters[]// [1] LegReturnRateValuationDateBusinessCenter.42570
}
