import { ILegMarketDisruptionFallbackReferencePriceGrpNoLegMarketDisruptionFallbackReferencePrices } from './leg_market_disruption_fallback_reference_price_grp_no_leg_market_disruption_fallback_reference_prices'

export interface ILegMarketDisruptionFallbackReferencePriceGrp {
  NoLegMarketDisruptionFallbackReferencePrices?: ILegMarketDisruptionFallbackReferencePriceGrpNoLegMarketDisruptionFallbackReferencePrices[]// [1] LegMarketDisruptionFallbackUnderlierType.41472, LegMarketDisruptionFallbackUnderlierSecurityID.41473 .. LegMarketDisruptionFallbackBasketDivisor.41480
}
