export interface ILegOptionExerciseDates {
  LegOptionExerciseBusinessDayConvention?: number// [1] 41493 (Int)
  LegOptionExerciseEarliestDateOffsetDayType?: number// [2] 41494 (Int)
  LegOptionExerciseEarliestDateOffsetPeriod?: number// [3] 41495 (Int)
  LegOptionExerciseEarliestDateOffsetUnit?: string// [4] 41496 (String)
  LegOptionExerciseFrequencyPeriod?: number// [5] 41497 (Int)
  LegOptionExerciseFrequencyUnit?: string// [6] 41498 (String)
  LegOptionExerciseStartDateUnadjusted?: Date// [7] 41499 (LocalDate)
  LegOptionExerciseStartDateRelativeTo?: number// [8] 41500 (Int)
  LegOptionExerciseStartDateOffsetPeriod?: number// [9] 41501 (Int)
  LegOptionExerciseStartDateOffsetUnit?: string// [10] 41502 (String)
  LegOptionExerciseStartDateOffsetDayType?: number// [11] 41503 (Int)
  LegOptionExerciseStartDateAdjusted?: Date// [12] 41504 (LocalDate)
  LegOptionExerciseSkip?: number// [13] 41505 (Int)
  LegOptionExerciseNominationDeadline?: Date// [14] 41506 (LocalDate)
  LegOptionExerciseFirstDateUnadjusted?: Date// [15] 41507 (LocalDate)
  LegOptionExerciseLastDateUnadjusted?: Date// [16] 41508 (LocalDate)
  LegOptionExerciseEarliestTime?: string// [17] 41509 (String)
  LegOptionExerciseLatestTime?: string// [18] 41510 (String)
  LegOptionExerciseTimeBusinessCenter?: string// [19] 41511 (String)
}
