export interface ILegPaymentStreamNonDeliverableFixingDatesBusinessCenterGrpNoLegPaymentStreamNonDeliverableFixingDateBusinessCenters {
  LegPaymentStreamNonDeliverableFixingDatesBusinessCenter?: string// [1] 40361 (String)
}
