import { ILegProtectionTermEventQualifierGrpNoLegProtectionTermEventQualifiers } from './leg_protection_term_event_qualifier_grp_no_leg_protection_term_event_qualifiers'

export interface ILegProtectionTermEventQualifierGrp {
  NoLegProtectionTermEventQualifiers?: ILegProtectionTermEventQualifierGrpNoLegProtectionTermEventQualifiers[]// [1] LegProtectionTermEventQualifier.41634
}
