import { ILegProvisionCashSettlValueDateBusinessCenterGrpNoLegProvisionCashSettlValueDateBusinessCenters } from './leg_provision_cash_settl_value_date_business_center_grp_no_leg_provision_cash_settl_value_date_business_centers'

export interface ILegProvisionCashSettlValueDateBusinessCenterGrp {
  NoLegProvisionCashSettlValueDateBusinessCenters?: ILegProvisionCashSettlValueDateBusinessCenterGrpNoLegProvisionCashSettlValueDateBusinessCenters[]// [1] LegProvisionCashSettlValueDateBusinessCenter.40527
}
