import { ILegOptionExerciseExpirationDateGrpNoLegOptionExerciseExpirationDates } from './leg_option_exercise_expiration_date_grp_no_leg_option_exercise_expiration_dates'

export interface ILegOptionExerciseExpirationDateGrp {
  NoLegOptionExerciseExpirationDates?: ILegOptionExerciseExpirationDateGrpNoLegOptionExerciseExpirationDates[]// [1] LegOptionExerciseExpirationDate.41528, LegOptionExerciseExpirationDateType.41529
}
