import { IMandatoryClearingJurisdictionGrpNoMandatoryClearingJurisdictions } from './mandatory_clearing_jurisdiction_grp_no_mandatory_clearing_jurisdictions'

export interface IMandatoryClearingJurisdictionGrp {
  NoMandatoryClearingJurisdictions?: IMandatoryClearingJurisdictionGrpNoMandatoryClearingJurisdictions[]// [1] MandatoryClearingJurisdiction.41313
}
