import { IOptionExerciseExpirationDateGrpNoOptionExerciseExpirationDates } from './option_exercise_expiration_date_grp_no_option_exercise_expiration_dates'

export interface IOptionExerciseExpirationDateGrp {
  NoOptionExerciseExpirationDates?: IOptionExerciseExpirationDateGrpNoOptionExerciseExpirationDates[]// [1] OptionExerciseExpirationDate.41153, OptionExerciseExpirationDateType.41154
}
