export interface IOptionExerciseDates {
  OptionExerciseBusinessDayConvention?: number// [1] 41118 (Int)
  OptionExerciseEarliestDateOffsetDayType?: number// [2] 41119 (Int)
  OptionExerciseEarliestDateOffsetPeriod?: number// [3] 41120 (Int)
  OptionExerciseEarliestDateOffsetUnit?: string// [4] 41121 (String)
  OptionExerciseFrequencyPeriod?: number// [5] 41122 (Int)
  OptionExerciseFrequencyUnit?: string// [6] 41123 (String)
  OptionExerciseStartDateUnadjusted?: Date// [7] 41124 (LocalDate)
  OptionExerciseStartDateRelativeTo?: number// [8] 41125 (Int)
  OptionExerciseStartDateOffsetPeriod?: number// [9] 41126 (Int)
  OptionExerciseStartDateOffsetUnit?: string// [10] 41127 (String)
  OptionExerciseStartDateOffsetDayType?: number// [11] 41128 (Int)
  OptionExerciseStartDateAdjusted?: Date// [12] 41129 (LocalDate)
  OptionExerciseSkip?: number// [13] 41130 (Int)
  OptionExerciseNominationDeadline?: Date// [14] 41131 (LocalDate)
  OptionExerciseFirstDateUnadjusted?: Date// [15] 41132 (LocalDate)
  OptionExerciseLastDateUnadjusted?: Date// [16] 41133 (LocalDate)
  OptionExerciseEarliestTime?: string// [17] 41134 (String)
  OptionExerciseLatestTime?: string// [18] 41135 (String)
  OptionExerciseTimeBusinessCenter?: string// [19] 41136 (String)
}
