export interface IPaymentStreamResetDates {
  PaymentStreamResetDateRelativeTo?: number// [1] 40761 (Int)
  PaymentStreamResetDateBusinessDayConvention?: number// [2] 40762 (Int)
  PaymentStreamResetFrequencyPeriod?: number// [3] 40764 (Int)
  PaymentStreamResetFrequencyUnit?: string// [4] 40765 (String)
  PaymentStreamResetWeeklyRollConvention?: string// [5] 40766 (String)
  PaymentStreamInitialFixingDateRelativeTo?: number// [6] 40767 (Int)
  PaymentStreamInitialFixingDateBusinessDayConvention?: number// [7] 40768 (Int)
  PaymentStreamInitialFixingDateOffsetPeriod?: number// [8] 40770 (Int)
  PaymentStreamInitialFixingDateOffsetUnit?: string// [9] 40771 (String)
  PaymentStreamInitialFixingDateOffsetDayType?: number// [10] 40772 (Int)
  PaymentStreamInitialFixingDateAdjusted?: Date// [11] 40773 (LocalDate)
  PaymentStreamFixingDateRelativeTo?: number// [12] 40774 (Int)
  PaymentStreamFixingDateBusinessDayConvention?: number// [13] 40775 (Int)
  PaymentStreamFixingDateOffsetPeriod?: number// [14] 40777 (Int)
  PaymentStreamFixingDateOffsetUnit?: string// [15] 40778 (String)
  PaymentStreamFixingDateOffsetDayType?: number// [16] 40779 (Int)
  PaymentStreamFixingDateAdjusted?: Date// [17] 40780 (LocalDate)
  PaymentStreamRateCutoffDateOffsetPeriod?: number// [18] 40781 (Int)
  PaymentStreamRateCutoffDateOffsetUnit?: string// [19] 40782 (String)
  PaymentStreamRateCutoffDateOffsetDayType?: number// [20] 40783 (Int)
}
