import { IPaymentScheduleInterimExchangeDateBusinessCenterGrpNoPaymentScheduleInterimExchangeDateBusinessCenters } from './payment_schedule_interim_exchange_date_business_center_grp_no_payment_schedule_interim_exchange_date_business_centers'

export interface IPaymentScheduleInterimExchangeDateBusinessCenterGrp {
  NoPaymentScheduleInterimExchangeDateBusinessCenters?: IPaymentScheduleInterimExchangeDateBusinessCenterGrpNoPaymentScheduleInterimExchangeDateBusinessCenters[]// [1] PaymentScheduleInterimExchangeDatesBusinessCenter.40863
}
