export interface IPaymentStreamCompoundingFloatingRate {
  PaymentStreamCompoundingRateIndex?: string// [1] 42628 (String)
  PaymentStreamCompoundingRateIndexCurvePeriod?: number// [2] 42629 (Int)
  PaymentStreamCompoundingRateIndexCurveUnit?: string// [3] 42630 (String)
  PaymentStreamCompoundingRateMultiplier?: number// [4] 42631 (Float)
  PaymentStreamCompoundingRateSpread?: number// [5] 42632 (Float)
  PaymentStreamCompoundingRateSpreadPositionType?: number// [6] 42633 (Int)
  PaymentStreamCompoundingRateTreatment?: number// [7] 42634 (Int)
  PaymentStreamCompoundingCapRate?: number// [8] 42635 (Float)
  PaymentStreamCompoundingCapRateBuySide?: number// [9] 42636 (Int)
  PaymentStreamCompoundingCapRateSellSide?: number// [10] 42637 (Int)
  PaymentStreamCompoundingFloorRate?: number// [11] 42638 (Float)
  PaymentStreamCompoundingFloorRateBuySide?: number// [12] 42639 (Int)
  PaymentStreamCompoundingFloorRateSellSide?: number// [13] 42640 (Int)
  PaymentStreamCompoundingInitialRate?: number// [14] 42641 (Float)
  PaymentStreamCompoundingFinalRateRoundingDirection?: string// [15] 42642 (String)
  PaymentStreamCompoundingFinalRatePrecision?: number// [16] 42643 (Int)
  PaymentStreamCompoundingAveragingMethod?: number// [17] 42644 (Int)
  PaymentStreamCompoundingNegativeRateTreatment?: number// [18] 42645 (Int)
}
