import { IPaymentStubEndDateBusinessCenterGrpNoPaymentStubEndDateBusinessCenters } from './payment_stub_end_date_business_center_grp_no_payment_stub_end_date_business_centers'

export interface IPaymentStubEndDateBusinessCenterGrp {
  NoPaymentStubEndDateBusinessCenters?: IPaymentStubEndDateBusinessCenterGrpNoPaymentStubEndDateBusinessCenters[]// [1] PaymentStubEndDateBusinessCenter.42697
}
