import { IPaymentStreamInitialFixingDateBusinessCenterGrpNoPaymentStreamInitialFixingDateBusinessCenters } from './payment_stream_initial_fixing_date_business_center_grp_no_payment_stream_initial_fixing_date_business_centers'

export interface IPaymentStreamInitialFixingDateBusinessCenterGrp {
  NoPaymentStreamInitialFixingDateBusinessCenters?: IPaymentStreamInitialFixingDateBusinessCenterGrpNoPaymentStreamInitialFixingDateBusinessCenters[]// [1] PaymentStreamInitialFixingDateBusinessCenter.40769
}
