import { IPaymentStreamNonDeliverableFixingDatesBusinessCenterGrpNoPaymentStreamNonDeliverableFixingDatesBusinessCenters } from './payment_stream_non_deliverable_fixing_dates_business_center_grp_no_payment_stream_non_deliverable_fixing_dates_business_centers'

export interface IPaymentStreamNonDeliverableFixingDatesBusinessCenterGrp {
  NoPaymentStreamNonDeliverableFixingDatesBusinessCenters?: IPaymentStreamNonDeliverableFixingDatesBusinessCenterGrpNoPaymentStreamNonDeliverableFixingDatesBusinessCenters[]// [1] PaymentStreamNonDeliverableFixingDatesBusinessCenter.40819
}
