import { IProvisionOptionRelevantUnderlyingDateBusinessCenterGrpNoProvisionOptionRelevantUnderlyingDateBusinessCenters } from './provision_option_relevant_underlying_date_business_center_grp_no_provision_option_relevant_underlying_date_business_centers'

export interface IProvisionOptionRelevantUnderlyingDateBusinessCenterGrp {
  NoProvisionOptionRelevantUnderlyingDateBusinessCenters?: IProvisionOptionRelevantUnderlyingDateBusinessCenterGrpNoProvisionOptionRelevantUnderlyingDateBusinessCenters[]// [1] ProvisionOptionRelevantUnderlyingDateBusinessCenter.40157
}
