import { IProvisionOptionExerciseFixedDateGrpNoProvisionOptionExerciseFixedDates } from './provision_option_exercise_fixed_date_grp_no_provision_option_exercise_fixed_dates'

export interface IProvisionOptionExerciseFixedDateGrp {
  NoProvisionOptionExerciseFixedDates?: IProvisionOptionExerciseFixedDateGrpNoProvisionOptionExerciseFixedDates[]// [1] ProvisionOptionExerciseFixedDate.40143, ProvisionOptionExerciseFixedDateType.40144
}
