import { IReturnRateInformationSourceGrpNoReturnRateInformationSources } from './return_rate_information_source_grp_no_return_rate_information_sources'

export interface IReturnRateInformationSourceGrp {
  NoReturnRateInformationSources?: IReturnRateInformationSourceGrpNoReturnRateInformationSources[]// [1] ReturnRateInformationSource.42762, ReturnRateReferencePage.42763, ReturnRateReferencePageHeading.42764
}
