export interface IReturnRateDateGrpNoReturnRateDates {
  ReturnRateDateMode?: number// [1] 42710 (Int)
  ReturnRateValuationDateRelativeTo?: number// [2] 42711 (Int)
  ReturnRateValuationDateOffsetPeriod?: number// [3] 42712 (Int)
  ReturnRateValuationDateOffsetUnit?: string// [4] 42713 (String)
  ReturnRateValuationDateOffsetDayType?: number// [5] 42714 (Int)
  ReturnRateValuationStartDateUnadjusted?: Date// [6] 42715 (LocalDate)
  ReturnRateValuationStartDateRelativeTo?: number// [7] 42716 (Int)
  ReturnRateValuationStartDateOffsetPeriod?: number// [8] 42717 (Int)
  ReturnRateValuationStartDateOffsetUnit?: string// [9] 42718 (String)
  ReturnRateValuationStartDateOffsetDayType?: number// [10] 42719 (Int)
  ReturnRateValuationStartDateAdjusted?: Date// [11] 42720 (LocalDate)
  ReturnRateValuationEndDateUnadjusted?: Date// [12] 42721 (LocalDate)
  ReturnRateValuationEndDateRelativeTo?: number// [13] 42722 (Int)
  ReturnRateValuationEndDateOffsetPeriod?: number// [14] 42723 (Int)
  ReturnRateValuationEndDateOffsetUnit?: string// [15] 42724 (String)
  ReturnRateValuationEndDateOffsetDayType?: number// [16] 42725 (Int)
  ReturnRateValuationEndDateAdjusted?: Date// [17] 42726 (LocalDate)
  ReturnRateValuationFrequencyPeriod?: number// [18] 42727 (Int)
  ReturnRateValuationFrequencyUnit?: string// [19] 42728 (String)
  ReturnRateValuationFrequencyRollConvention?: string// [20] 42729 (String)
  ReturnRateValuationDateBusinessDayConvention?: number// [21] 42730 (Int)
}
