import { ISettlMethodElectionDateBusinessCenterGrpNoSettlMethodElectionDateBusinessCenters } from './settl_method_election_date_business_center_grp_no_settl_method_election_date_business_centers'

export interface ISettlMethodElectionDateBusinessCenterGrp {
  NoSettlMethodElectionDateBusinessCenters?: ISettlMethodElectionDateBusinessCenterGrpNoSettlMethodElectionDateBusinessCenters[]// [1] SettlMethodElectionDateBusinessCenter.42776
}
