import { IUnderlyingProtectionTermEventNewsSourceGrpNoUnderlyingProtectionTermEventNewsSources } from './underlying_protection_term_event_news_source_grp_no_underlying_protection_term_event_news_sources'

export interface IUnderlyingProtectionTermEventNewsSourceGrp {
  NoUnderlyingProtectionTermEventNewsSources?: IUnderlyingProtectionTermEventNewsSourceGrpNoUnderlyingProtectionTermEventNewsSources[]// [1] UnderlyingProtectionTermEventNewsSource.42091
}
