import { IUnderlyingStreamTerminationDateBusinessCenterGrpNoUnderlyingStreamTerminationDateBusinessCenters } from './underlying_stream_termination_date_business_center_grp_no_underlying_stream_termination_date_business_centers'

export interface IUnderlyingStreamTerminationDateBusinessCenterGrp {
  NoUnderlyingStreamTerminationDateBusinessCenters?: IUnderlyingStreamTerminationDateBusinessCenterGrpNoUnderlyingStreamTerminationDateBusinessCenters[]// [1] UnderlyingStreamTerminationDateBusinessCenter.40550
}
