import { IUnderlyingPaymentStreamPricingBusinessCenterGrpNoUnderlyingPaymentStreamPricingBusinessCenters } from './underlying_payment_stream_pricing_business_center_grp_no_underlying_payment_stream_pricing_business_centers'

export interface IUnderlyingPaymentStreamPricingBusinessCenterGrp {
  NoUnderlyingPaymentStreamPricingBusinessCenters?: IUnderlyingPaymentStreamPricingBusinessCenterGrpNoUnderlyingPaymentStreamPricingBusinessCenters[]// [1] UnderlyingPaymentStreamPricingBusinessCenter.41910
}
