import { IUnderlyingStreamCommoditySettlTimeGrpNoUnderlyingStreamCommoditySettlTimes } from './underlying_stream_commodity_settl_time_grp_no_underlying_stream_commodity_settl_times'

export interface IUnderlyingStreamCommoditySettlTimeGrp {
  NoUnderlyingStreamCommoditySettlTimes?: IUnderlyingStreamCommoditySettlTimeGrpNoUnderlyingStreamCommoditySettlTimes[]// [1] UnderlyingStreamCommoditySettlStart.42000, UnderlyingStreamCommoditySettlEnd.42001, UnderlyingStreamCommoditySettlTimeType.41936
}
