import { IUnderlyingProvisionCashSettlPaymentDateBusinessCenterGrpNoUnderlyingProvisionCashSettlPaymentDateBusinessCenters } from './underlying_provision_cash_settl_payment_date_business_center_grp_no_underlying_provision_cash_settl_payment_date_business_centers'

export interface IUnderlyingProvisionCashSettlPaymentDateBusinessCenterGrp {
  NoUnderlyingProvisionCashSettlPaymentDateBusinessCenters?: IUnderlyingProvisionCashSettlPaymentDateBusinessCenterGrpNoUnderlyingProvisionCashSettlPaymentDateBusinessCenters[]// [1] UnderlyingProvisionCashSettlPaymentDateBusinessCenter.42181
}
