import { IUnderlyingDividendPeriodBusinessCenterGrpNoUnderlyingDividendPeriodBusinessCenters } from './underlying_dividend_period_business_center_grp_no_underlying_dividend_period_business_centers'

export interface IUnderlyingDividendPeriodBusinessCenterGrp {
  NoUnderlyingDividendPeriodBusinessCenters?: IUnderlyingDividendPeriodBusinessCenterGrpNoUnderlyingDividendPeriodBusinessCenters[]// [1] UnderlyingDividendPeriodBusinessCenter.42883
}
