export interface IUnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenterGrpNoUnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenters {
  UnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenter?: string// [1] 42189 (String)
}
