import { IUnderlyingReturnRateDateGrpNoUnderlyingReturnRateDates } from './underlying_return_rate_date_grp_no_underlying_return_rate_dates'

export interface IUnderlyingReturnRateDateGrp {
  NoUnderlyingReturnRateDates?: IUnderlyingReturnRateDateGrpNoUnderlyingReturnRateDates[]// [1] UnderlyingReturnRateDateMode.43009, UnderlyingReturnRateValuationDateRelativeTo.43010 .. UnderlyingReturnRateValuationDateBusinessDayConvention.43029
}
