import { IUnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenterGrpNoUnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenters } from './underlying_provision_option_relevant_underlying_date_business_center_grp_no_underlying_provision_option_relevant_underlying_date_business_centers'

export interface IUnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenterGrp {
  NoUnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenters?: IUnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenterGrpNoUnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenters[]// [1] UnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenter.42189
}
