import { IUnderlyingPaymentStreamPaymentDateBusinessCenterGrpNoUnderlyingPaymentStreamPaymentDateBusinessCenters } from './underlying_payment_stream_payment_date_business_center_grp_no_underlying_payment_stream_payment_date_business_centers'

export interface IUnderlyingPaymentStreamPaymentDateBusinessCenterGrp {
  NoUnderlyingPaymentStreamPaymentDateBusinessCenters?: IUnderlyingPaymentStreamPaymentDateBusinessCenterGrpNoUnderlyingPaymentStreamPaymentDateBusinessCenters[]// [1] UnderlyingPaymentStreamPaymentDateBusinessCenter.40582
}
