import { IUnderlyingPaymentScheduleInterimExchangeDateBusinessCenterGrpNoUnderlyingPaymentScheduleInterimExchangeDateBusinessCenters } from './underlying_payment_schedule_interim_exchange_date_business_center_grp_no_underlying_payment_schedule_interim_exchange_date_business_centers'

export interface IUnderlyingPaymentScheduleInterimExchangeDateBusinessCenterGrp {
  NoUnderlyingPaymentScheduleInterimExchangeDateBusinessCenters?: IUnderlyingPaymentScheduleInterimExchangeDateBusinessCenterGrpNoUnderlyingPaymentScheduleInterimExchangeDateBusinessCenters[]// [1] UnderlyingPaymentScheduleInterimExchangeDatesBusinessCenter.40699
}
