import { IUnderlyingProvisionDateBusinessCenterGrpNoUnderlyingProvisionDateBusinessCenters } from './underlying_provision_date_business_center_grp_no_underlying_provision_date_business_centers'

export interface IUnderlyingProvisionDateBusinessCenterGrp {
  NoUnderlyingProvisionDateBusinessCenters?: IUnderlyingProvisionDateBusinessCenterGrpNoUnderlyingProvisionDateBusinessCenters[]// [1] UnderlyingProvisionDateBusinessCenter.42191
}
