export interface IUnderlyingProvisionCashSettlPaymentDateBusinessCenterGrpNoUnderlyingProvisionCashSettlPaymentDateBusinessCenters {
  UnderlyingProvisionCashSettlPaymentDateBusinessCenter?: string// [1] 42181 (String)
}
