import { IUnderlyingProvisionOptionExerciseBusinessCenterGrpNoUnderlyingProvisionOptionExerciseBusinessCenters } from './underlying_provision_option_exercise_business_center_grp_no_underlying_provision_option_exercise_business_centers'

export interface IUnderlyingProvisionOptionExerciseBusinessCenterGrp {
  NoUnderlyingProvisionOptionExerciseBusinessCenters?: IUnderlyingProvisionOptionExerciseBusinessCenterGrpNoUnderlyingProvisionOptionExerciseBusinessCenters[]// [1] UnderlyingProvisionOptionExerciseBusinessCenter.42185
}
