import { IUnderlyingReturnRateValuationDateBusinessCenterGrpNoUnderlyingReturnRateValuationDateBusinessCenters } from './underlying_return_rate_valuation_date_business_center_grp_no_underlying_return_rate_valuation_date_business_centers'

export interface IUnderlyingReturnRateValuationDateBusinessCenterGrp {
  NoUnderlyingReturnRateValuationDateBusinessCenters?: IUnderlyingReturnRateValuationDateBusinessCenterGrpNoUnderlyingReturnRateValuationDateBusinessCenters[]// [1] UnderlyingReturnRateValuationDateBusinessCenter.43070
}
