export interface IUnderlyingPaymentStreamCompoundingFloatingRate {
  UnderlyingPaymentStreamCompoundingRateIndex?: string// [1] 42923 (String)
  UnderlyingPaymentStreamCompoundingRateIndexCurvePeriod?: number// [2] 42924 (Int)
  UnderlyingPaymentStreamCompoundingRateIndexCurveUnit?: string// [3] 42925 (String)
  UnderlyingPaymentStreamCompoundingRateMultiplier?: number// [4] 42926 (Float)
  UnderlyingPaymentStreamCompoundingRateSpread?: number// [5] 42927 (Float)
  UnderlyingPaymentStreamCompoundingRateSpreadPositionType?: number// [6] 42928 (Int)
  UnderlyingPaymentStreamCompoundingRateTreatment?: number// [7] 42929 (Int)
  UnderlyingPaymentStreamCompoundingCapRate?: number// [8] 42930 (Float)
  UnderlyingPaymentStreamCompoundingCapRateBuySide?: number// [9] 42931 (Int)
  UnderlyingPaymentStreamCompoundingCapRateSellSide?: number// [10] 42932 (Int)
  UnderlyingPaymentStreamCompoundingFloorRate?: number// [11] 42933 (Float)
  UnderlyingPaymentStreamCompoundingFloorRateBuySide?: number// [12] 42934 (Int)
  UnderlyingPaymentStreamCompoundingFloorRateSellSide?: number// [13] 42935 (Int)
  UnderlyingPaymentStreamCompoundingInitialRate?: number// [14] 42936 (Float)
  UnderlyingPaymentStreamCompoundingFinalRateRoundingDirection?: string// [15] 42937 (String)
  UnderlyingPaymentStreamCompoundingFinalRatePrecision?: number// [16] 42938 (Int)
  UnderlyingPaymentStreamCompoundingAveragingMethod?: number// [17] 42939 (Int)
  UnderlyingPaymentStreamCompoundingNegativeRateTreatment?: number// [18] 42940 (Int)
}
