import { IUnderlyingComplexEventDateBusinessCenterGrpNoUnderlyingComplexEventDateBusinessCenters } from './underlying_complex_event_date_business_center_grp_no_underlying_complex_event_date_business_centers'

export interface IUnderlyingComplexEventDateBusinessCenterGrp {
  NoUnderlyingComplexEventDateBusinessCenters?: IUnderlyingComplexEventDateBusinessCenterGrpNoUnderlyingComplexEventDateBusinessCenters[]// [1] UnderlyingComplexEventDateBusinessCenter.41738
}
