import { IUnderlyingStreamCalculationPeriodBusinessCenterGrpNoUnderlyingStreamCalculationPeriodBusinessCenters } from './underlying_stream_calculation_period_business_center_grp_no_underlying_stream_calculation_period_business_centers'

export interface IUnderlyingStreamCalculationPeriodBusinessCenterGrp {
  NoUnderlyingStreamCalculationPeriodBusinessCenters?: IUnderlyingStreamCalculationPeriodBusinessCenterGrpNoUnderlyingStreamCalculationPeriodBusinessCenters[]// [1] UnderlyingStreamCalculationPeriodBusinessCenter.40557
}
