import { IUnderlyingComplexEventCreditEventQualifierGrpNoUnderlyingComplexEventCreditEventQualifiers } from './underlying_complex_event_credit_event_qualifier_grp_no_underlying_complex_event_credit_event_qualifiers'

export interface IUnderlyingComplexEventCreditEventQualifierGrp {
  NoUnderlyingComplexEventCreditEventQualifiers?: IUnderlyingComplexEventCreditEventQualifierGrpNoUnderlyingComplexEventCreditEventQualifiers[]// [1] UnderlyingComplexEventCreditEventQualifier.41725
}
