import { IUnderlyingComplexEventPeriodDateGrpNoUnderlyingComplexEventPeriodDateTimes } from './underlying_complex_event_period_date_grp_no_underlying_complex_event_period_date_times'

export interface IUnderlyingComplexEventPeriodDateGrp {
  NoUnderlyingComplexEventPeriodDateTimes?: IUnderlyingComplexEventPeriodDateGrpNoUnderlyingComplexEventPeriodDateTimes[]// [1] UnderlyingComplexEventPeriodDate.41727, UnderlyingComplexEventPeriodTime.41728
}
