import { IUnderlyingProvisionOptionExpirationDateBusinessCenterGrpNoUnderlyingProvisionOptionExpirationDateBusinessCenters } from './underlying_provision_option_expiration_date_business_center_grp_no_underlying_provision_option_expiration_date_business_centers'

export interface IUnderlyingProvisionOptionExpirationDateBusinessCenterGrp {
  NoUnderlyingProvisionOptionExpirationDateBusinessCenters?: IUnderlyingProvisionOptionExpirationDateBusinessCenterGrpNoUnderlyingProvisionOptionExpirationDateBusinessCenters[]// [1] UnderlyingProvisionOptionExpirationDateBusinessCenter.42187
}
