import { IUnderlyingSettlMethodElectionDateBusinessCenterGrpNoUnderlyingSettlMethodElectionDateBusinessCenters } from './underlying_settl_method_election_date_business_center_grp_no_underlying_settl_method_election_date_business_centers'

export interface IUnderlyingSettlMethodElectionDateBusinessCenterGrp {
  NoUnderlyingSettlMethodElectionDateBusinessCenters?: IUnderlyingSettlMethodElectionDateBusinessCenterGrpNoUnderlyingSettlMethodElectionDateBusinessCenters[]// [1] UnderlyingSettlMethodElectionDateBusinessCenter.43075
}
