import { IUnderlyingPaymentStreamNonDeliverableFixingDatesBusinessCenterGrpNoUnderlyingPaymentStreamNonDeliverableFixingDatesBizCenters } from './underlying_payment_stream_non_deliverable_fixing_dates_business_center_grp_no_underlying_payment_stream_non_deliverable_fixing_dates_biz_centers'

export interface IUnderlyingPaymentStreamNonDeliverableFixingDatesBusinessCenterGrp {
  NoUnderlyingPaymentStreamNonDeliverableFixingDatesBizCenters?: IUnderlyingPaymentStreamNonDeliverableFixingDatesBusinessCenterGrpNoUnderlyingPaymentStreamNonDeliverableFixingDatesBizCenters[]// [1] UnderlyingPaymentStreamNonDeliverableFixingDatesBusinessCenter.40650
}
