import { IUnderlyingOptionExerciseBusinessCenterGrpNoUnderlyingOptionExerciseBusinessCenters } from './underlying_option_exercise_business_center_grp_no_underlying_option_exercise_business_centers'

export interface IUnderlyingOptionExerciseBusinessCenterGrp {
  NoUnderlyingOptionExerciseBusinessCenters?: IUnderlyingOptionExerciseBusinessCenterGrpNoUnderlyingOptionExerciseBusinessCenters[]// [1] UnderlyingOptionExerciseBusinessCenter.41821
}
