export interface IUnderlyingReturnRateDateGrpNoUnderlyingReturnRateDates {
  UnderlyingReturnRateDateMode?: number// [1] 43009 (Int)
  UnderlyingReturnRateValuationDateRelativeTo?: number// [2] 43010 (Int)
  UnderlyingReturnRateValuationDateOffsetPeriod?: number// [3] 43011 (Int)
  UnderlyingReturnRateValuationDateOffsetUnit?: string// [4] 43012 (String)
  UnderlyingReturnRateValuationDateOffsetDayType?: number// [5] 43013 (Int)
  UnderlyingReturnRateValuationStartDateUnadjusted?: Date// [6] 43014 (LocalDate)
  UnderlyingReturnRateValuationStartDateRelativeTo?: number// [7] 43015 (Int)
  UnderlyingReturnRateValuationStartDateOffsetPeriod?: number// [8] 43016 (Int)
  UnderlyingReturnRateValuationStartDateOffsetUnit?: string// [9] 43017 (String)
  UnderlyingReturnRateValuationStartDateOffsetDayType?: number// [10] 43018 (Int)
  UnderlyingReturnRateValuationStartDateAdjusted?: Date// [11] 43019 (LocalDate)
  UnderlyingReturnRateValuationEndDateUnadjusted?: Date// [12] 43020 (LocalDate)
  UnderlyingReturnRateValuationEndDateRelativeTo?: number// [13] 43021 (Int)
  UnderlyingReturnRateValuationEndDateOffsetPeriod?: number// [14] 43022 (Int)
  UnderlyingReturnRateValuationEndDateOffsetUnit?: string// [15] 43023 (String)
  UnderlyingReturnRateValuationEndDateOffsetDayType?: number// [16] 43024 (Int)
  UnderlyingReturnRateValuationEndDateAdjusted?: Date// [17] 43025 (LocalDate)
  UnderlyingReturnRateValuationFrequencyPeriod?: number// [18] 43026 (Int)
  UnderlyingReturnRateValuationFrequencyUnit?: string// [19] 43027 (String)
  UnderlyingReturnRateValuationFrequencyRollConvention?: string// [20] 43028 (String)
  UnderlyingReturnRateValuationDateBusinessDayConvention?: number// [21] 43029 (Int)
}
