import { IUnderlyingPaymentStreamPricingDateGrpNoUnderlyingPaymentStreamPricingDates } from './underlying_payment_stream_pricing_date_grp_no_underlying_payment_stream_pricing_dates'

export interface IUnderlyingPaymentStreamPricingDateGrp {
  NoUnderlyingPaymentStreamPricingDates?: IUnderlyingPaymentStreamPricingDateGrpNoUnderlyingPaymentStreamPricingDates[]// [1] UnderlyingPaymentStreamPricingDate.41942, UnderlyingPaymentStreamPricingDateType.41943
}
