import { IUnderlyingSettlRateDisruptionFallbackGrpNoUnderlyingSettlRateFallbacks } from './underlying_settl_rate_disruption_fallback_grp_no_underlying_settl_rate_fallbacks'

export interface IUnderlyingSettlRateDisruptionFallbackGrp {
  NoUnderlyingSettlRateFallbacks?: IUnderlyingSettlRateDisruptionFallbackGrpNoUnderlyingSettlRateFallbacks[]// [1] UnderlyingSettlRatePostponementMaximumDays.40660, UnderlyingSettlRateFallbackRateSource.40904 .. UnderlyingSettlRatePostponementCalculationAgent.40663
}
