import { IUnderlyingProvisionCashSettlValueDateBusinessCenterGrpNoUnderlyingProvisionCashSettlValueDateBusinessCenters } from './underlying_provision_cash_settl_value_date_business_center_grp_no_underlying_provision_cash_settl_value_date_business_centers'

export interface IUnderlyingProvisionCashSettlValueDateBusinessCenterGrp {
  NoUnderlyingProvisionCashSettlValueDateBusinessCenters?: IUnderlyingProvisionCashSettlValueDateBusinessCenterGrpNoUnderlyingProvisionCashSettlValueDateBusinessCenters[]// [1] UnderlyingProvisionCashSettlValueDateBusinessCenter.42183
}
