import { IUnderlyingProvisionCashSettlPaymentFixedDateGrpNoUnderlyingProvisionCashSettlPaymentDates } from './underlying_provision_cash_settl_payment_fixed_date_grp_no_underlying_provision_cash_settl_payment_dates'

export interface IUnderlyingProvisionCashSettlPaymentFixedDateGrp {
  NoUnderlyingProvisionCashSettlPaymentDates?: IUnderlyingProvisionCashSettlPaymentFixedDateGrpNoUnderlyingProvisionCashSettlPaymentDates[]// [1] UnderlyingProvisionCashSettlPaymentDate.42100, UnderlyingProvisionCashSettlPaymentDateType.42101
}
