import { IUnderlyingPaymentStreamCompoundingDatesBusinessCenterGrpNoUnderlyingPaymentStreamCompoundingDatesBusinessCenters } from './underlying_payment_stream_compounding_dates_business_center_grp_no_underlying_payment_stream_compounding_dates_business_centers'

export interface IUnderlyingPaymentStreamCompoundingDatesBusinessCenterGrp {
  NoUnderlyingPaymentStreamCompoundingDatesBusinessCenters?: IUnderlyingPaymentStreamCompoundingDatesBusinessCenterGrpNoUnderlyingPaymentStreamCompoundingDatesBusinessCenters[]// [1] UnderlyingPaymentStreamCompoundingDatesBusinessCenter.42916
}
