import { IUnderlyingPhysicalSettlDeliverableObligationGrpNoUnderlyingPhysicalSettlDeliverableObligations } from './underlying_physical_settl_deliverable_obligation_grp_no_underlying_physical_settl_deliverable_obligations'

export interface IUnderlyingPhysicalSettlDeliverableObligationGrp {
  NoUnderlyingPhysicalSettlDeliverableObligations?: IUnderlyingPhysicalSettlDeliverableObligationGrpNoUnderlyingPhysicalSettlDeliverableObligations[]// [1] UnderlyingPhysicalSettlDeliverableObligationType.42066, UnderlyingPhysicalSettlDeliverableObligationValue.42067
}
