import { IUnderlyingPaymentStreamInitialFixingDateBusinessCenterGrpNoUnderlyingPaymentStreamInitialFixingDateBusinessCenters } from './underlying_payment_stream_initial_fixing_date_business_center_grp_no_underlying_payment_stream_initial_fixing_date_business_centers'

export interface IUnderlyingPaymentStreamInitialFixingDateBusinessCenterGrp {
  NoUnderlyingPaymentStreamInitialFixingDateBusinessCenters?: IUnderlyingPaymentStreamInitialFixingDateBusinessCenterGrpNoUnderlyingPaymentStreamInitialFixingDateBusinessCenters[]// [1] UnderlyingPaymentStreamInitialFixingDateBusinessCenter.40600
}
