import { IUnderlyingPaymentStreamFixingDateBusinessCenterGrpNoUnderlyingPaymentStreamFixingDateBusinessCenters } from './underlying_payment_stream_fixing_date_business_center_grp_no_underlying_payment_stream_fixing_date_business_centers'

export interface IUnderlyingPaymentStreamFixingDateBusinessCenterGrp {
  NoUnderlyingPaymentStreamFixingDateBusinessCenters?: IUnderlyingPaymentStreamFixingDateBusinessCenterGrpNoUnderlyingPaymentStreamFixingDateBusinessCenters[]// [1] UnderlyingPaymentStreamFixingDateBusinessCenter.40607
}
