import { IUnderlyingProvisionOptionExerciseFixedDateGrpNoUnderlyingProvisionOptionExerciseFixedDates } from './underlying_provision_option_exercise_fixed_date_grp_no_underlying_provision_option_exercise_fixed_dates'

export interface IUnderlyingProvisionOptionExerciseFixedDateGrp {
  NoUnderlyingProvisionOptionExerciseFixedDates?: IUnderlyingProvisionOptionExerciseFixedDateGrpNoUnderlyingProvisionOptionExerciseFixedDates[]// [1] UnderlyingProvisionOptionExerciseFixedDate.42113, UnderlyingProvisionOptionExerciseFixedDateType.42114
}
