import { IUnderlyingOptionExerciseExpirationDateBusinessCenterGrpNoUnderlyingOptionExerciseExpirationDateBusinessCenters } from './underlying_option_exercise_expiration_date_business_center_grp_no_underlying_option_exercise_expiration_date_business_centers'

export interface IUnderlyingOptionExerciseExpirationDateBusinessCenterGrp {
  NoUnderlyingOptionExerciseExpirationDateBusinessCenters?: IUnderlyingOptionExerciseExpirationDateBusinessCenterGrpNoUnderlyingOptionExerciseExpirationDateBusinessCenters[]// [1] UnderlyingOptionExerciseExpirationDateBusinessCenter.41845
}
