import { IUnderlyingMarketDisruptionFallbackReferencePriceGrpNoUnderlyingMarketDisruptionFallbackReferencePrices } from './underlying_market_disruption_fallback_reference_price_grp_no_underlying_market_disruption_fallback_reference_prices'

export interface IUnderlyingMarketDisruptionFallbackReferencePriceGrp {
  NoUnderlyingMarketDisruptionFallbackReferencePrices?: IUnderlyingMarketDisruptionFallbackReferencePriceGrpNoUnderlyingMarketDisruptionFallbackReferencePrices[]// [1] UnderlyingMarketDisruptionFallbackUnderlierType.41869, UnderlyingMarketDisruptionFallbackUnderlierSecurityID.41870 .. UnderlyingMarketDisruptionFallbackBasketDivisor.41877
}
