import { IUnderlyingAdditionalTermGrpNoUnderlyingAdditionalTerms } from './underlying_additional_term_grp_no_underlying_additional_terms'

export interface IUnderlyingAdditionalTermGrp {
  NoUnderlyingAdditionalTerms?: IUnderlyingAdditionalTermGrpNoUnderlyingAdditionalTerms[]// [1] UnderlyingAdditionalTermConditionPrecedentBondIndicator.42037, UnderlyingAdditionalTermDiscrepancyClauseIndicator.42038 .. UnderlyingAdditionalTermBondDayCount.42035
}
