import { IUnderlyingDeliveryScheduleSettlDayGrpNoUnderlyingDeliveryScheduleSettlDays } from './underlying_delivery_schedule_settl_day_grp_no_underlying_delivery_schedule_settl_days'

export interface IUnderlyingDeliveryScheduleSettlDayGrp {
  NoUnderlyingDeliveryScheduleSettlDays?: IUnderlyingDeliveryScheduleSettlDayGrpNoUnderlyingDeliveryScheduleSettlDays[]// [1] UnderlyingDeliveryScheduleSettlDay.41771, UnderlyingDeliveryScheduleSettlTotalHours.41772 .. UnderlyingDeliveryScheduleSettlTimeType.41776
}
