import { IUnderlyingStreamFirstPeriodStartDateBusinessCenterGrpNoUnderlyingStreamFirstPeriodStartDateBusinessCenters } from './underlying_stream_first_period_start_date_business_center_grp_no_underlying_stream_first_period_start_date_business_centers'

export interface IUnderlyingStreamFirstPeriodStartDateBusinessCenterGrp {
  NoUnderlyingStreamFirstPeriodStartDateBusinessCenters?: IUnderlyingStreamFirstPeriodStartDateBusinessCenterGrpNoUnderlyingStreamFirstPeriodStartDateBusinessCenters[]// [1] UnderlyingStreamFirstPeriodStartDateBusinessCenter.40560
}
