export interface IUnderlyingPaymentScheduleInterimExchangeDateBusinessCenterGrpNoUnderlyingPaymentScheduleInterimExchangeDateBusinessCenters {
  UnderlyingPaymentScheduleInterimExchangeDatesBusinessCenter?: string// [1] 40699 (String)
}
