import { IUnderlyingComplexEventAveragingObservationGrpNoUnderlyingComplexEventAveragingObservations } from './underlying_complex_event_averaging_observation_grp_no_underlying_complex_event_averaging_observations'

export interface IUnderlyingComplexEventAveragingObservationGrp {
  NoUnderlyingComplexEventAveragingObservations?: IUnderlyingComplexEventAveragingObservationGrpNoUnderlyingComplexEventAveragingObservations[]// [1] UnderlyingComplexEventAveragingObservationNumber.41714, UnderlyingComplexEventAveragingWeight.41715
}
