import { IUnderlyingMarketDisruptionEventGrpNoUnderlyingMarketDisruptionEvents } from './underlying_market_disruption_event_grp_no_underlying_market_disruption_events'

export interface IUnderlyingMarketDisruptionEventGrp {
  NoUnderlyingMarketDisruptionEvents?: IUnderlyingMarketDisruptionEventGrpNoUnderlyingMarketDisruptionEvents[]// [1] UnderlyingMarketDisruptionEvent.41865, UnderlyingMarketDisruptionValue.41338
}
