import { IUnderlyingProtectionTermObligationGrpNoUnderlyingProtectionTermObligations } from './underlying_protection_term_obligation_grp_no_underlying_protection_term_obligations'

export interface IUnderlyingProtectionTermObligationGrp {
  NoUnderlyingProtectionTermObligations?: IUnderlyingProtectionTermObligationGrpNoUnderlyingProtectionTermObligations[]// [1] UnderlyingProtectionTermObligationType.42088, UnderlyingProtectionTermObligationValue.42089
}
