import { IUnderlyingPaymentStreamResetDateBusinessCenterGrpNoUnderlyingPaymentStreamResetDateBusinessCenters } from './underlying_payment_stream_reset_date_business_center_grp_no_underlying_payment_stream_reset_date_business_centers'

export interface IUnderlyingPaymentStreamResetDateBusinessCenterGrp {
  NoUnderlyingPaymentStreamResetDateBusinessCenters?: IUnderlyingPaymentStreamResetDateBusinessCenterGrpNoUnderlyingPaymentStreamResetDateBusinessCenters[]// [1] UnderlyingPaymentStreamResetDateBusinessCenter.40594
}
