export interface IUnderlyingPaymentStreamInitialFixingDateBusinessCenterGrpNoUnderlyingPaymentStreamInitialFixingDateBusinessCenters {
  UnderlyingPaymentStreamInitialFixingDateBusinessCenter?: string// [1] 40600 (String)
}
