import { IUnderlyingDividendAccrualPaymentDateBusinessCenterGrpNoUnderlyingDividendAccrualPaymentDateBusinessCenters } from './underlying_dividend_accrual_payment_date_business_center_grp_no_underlying_dividend_accrual_payment_date_business_centers'

export interface IUnderlyingDividendAccrualPaymentDateBusinessCenterGrp {
  NoUnderlyingDividendAccrualPaymentDateBusinessCenters?: IUnderlyingDividendAccrualPaymentDateBusinessCenterGrpNoUnderlyingDividendAccrualPaymentDateBusinessCenters[]// [1] UnderlyingDividendAccrualPaymentDateBusinessCenter.42800
}
