import { IUnderlyingComplexEventCreditEventGrpNoUnderlyingComplexEventCreditEvents } from './underlying_complex_event_credit_event_grp_no_underlying_complex_event_credit_events'

export interface IUnderlyingComplexEventCreditEventGrp {
  NoUnderlyingComplexEventCreditEvents?: IUnderlyingComplexEventCreditEventGrpNoUnderlyingComplexEventCreditEvents[]// [1] UnderlyingComplexEventCreditEventType.41717, UnderlyingComplexEventCreditEventValue.41718 .. UnderlyingComplexEventCreditEventQualifier.41725
}
