export interface IUnderlyingPaymentStreamNonDeliverableFixingDatesBusinessCenterGrpNoUnderlyingPaymentStreamNonDeliverableFixingDatesBizCenters {
  UnderlyingPaymentStreamNonDeliverableFixingDatesBusinessCenter?: string// [1] 40650 (String)
}
