export interface IUnderlyingOptionExerciseDates {
  UnderlyingOptionExerciseBusinessDayConvention?: number// [1] 41822 (Int)
  UnderlyingOptionExerciseEarliestDateOffsetDayType?: number// [2] 41823 (Int)
  UnderlyingOptionExerciseEarliestDateOffsetPeriod?: number// [3] 41824 (Int)
  UnderlyingOptionExerciseEarliestDateOffsetUnit?: string// [4] 41825 (String)
  UnderlyingOptionExerciseFrequencyPeriod?: number// [5] 41826 (Int)
  UnderlyingOptionExerciseFrequencyUnit?: string// [6] 41827 (String)
  UnderlyingOptionExerciseStartDateUnadjusted?: Date// [7] 41828 (LocalDate)
  UnderlyingOptionExerciseStartDateRelativeTo?: number// [8] 41829 (Int)
  UnderlyingOptionExerciseStartDateOffsetPeriod?: number// [9] 41830 (Int)
  UnderlyingOptionExerciseStartDateOffsetUnit?: string// [10] 41831 (String)
  UnderlyingOptionExerciseStartDateOffsetDayType?: number// [11] 41832 (Int)
  UnderlyingOptionExerciseStartDateAdjusted?: Date// [12] 41833 (LocalDate)
  UnderlyingOptionExerciseSkip?: number// [13] 41834 (Int)
  UnderlyingOptionExerciseNominationDeadline?: Date// [14] 41835 (LocalDate)
  UnderlyingOptionExerciseFirstDateUnadjusted?: Date// [15] 41836 (LocalDate)
  UnderlyingOptionExerciseLastDateUnadjusted?: Date// [16] 41837 (LocalDate)
  UnderlyingOptionExerciseEarliestTime?: string// [17] 41838 (String)
  UnderlyingOptionExerciseLatestTime?: string// [18] 41839 (String)
  UnderlyingOptionExerciseTimeBusinessCenter?: string// [19] 41840 (String)
}
