import { IUnderlyingPaymentStubStartDateBusinessCenterGrpNoUnderlyingPaymentStubStartDateBusinessCenters } from './underlying_payment_stub_start_date_business_center_grp_no_underlying_payment_stub_start_date_business_centers'

export interface IUnderlyingPaymentStubStartDateBusinessCenterGrp {
  NoUnderlyingPaymentStubStartDateBusinessCenters?: IUnderlyingPaymentStubStartDateBusinessCenterGrpNoUnderlyingPaymentStubStartDateBusinessCenters[]// [1] UnderlyingPaymentStubStartDateBusinessCenter.43001
}
