import { IUnderlyingPaymentScheduleFixingDateBusinessCenterGrpNoUnderlyingPaymentScheduleFixingDateBusinessCenters } from './underlying_payment_schedule_fixing_date_business_center_grp_no_underlying_payment_schedule_fixing_date_business_centers'

export interface IUnderlyingPaymentScheduleFixingDateBusinessCenterGrp {
  NoUnderlyingPaymentScheduleFixingDateBusinessCenters?: IUnderlyingPaymentScheduleFixingDateBusinessCenterGrpNoUnderlyingPaymentScheduleFixingDateBusinessCenters[]// [1] UnderlyingPaymentScheduleFixingDateBusinessCenter.40690
}
