export interface IUnderlyingPaymentStreamCompoundingDatesBusinessCenterGrpNoUnderlyingPaymentStreamCompoundingDatesBusinessCenters {
  UnderlyingPaymentStreamCompoundingDatesBusinessCenter?: string// [1] 42916 (String)
}
