import { IUnderlyingStreamCommoditySettlBusinessCenterGrpNoUnderlyingStreamCommoditySettlBusinessCenters } from './underlying_stream_commodity_settl_business_center_grp_no_underlying_stream_commodity_settl_business_centers'

export interface IUnderlyingStreamCommoditySettlBusinessCenterGrp {
  NoUnderlyingStreamCommoditySettlBusinessCenters?: IUnderlyingStreamCommoditySettlBusinessCenterGrpNoUnderlyingStreamCommoditySettlBusinessCenters[]// [1] UnderlyingStreamCommoditySettlBusinessCenter.41963
}
