export interface IAdditionalTermBondRefGrp {
  AdditionalTermBondSecurityID?: string// [1] 40001 (String)
  SecurityIDSource?: string// [1] 22 (String)
  AdditionalTermBondDesc?: string// [1] 40003 (String)
  EncodedAdditionalTermBondDescLen?: number// [1] 40004 (Length)
  EncodedAdditionalTermBondDesc?: Buffer// [1] 40005 (RawData)
  AdditionalTermBondCurrency?: string// [1] 40006 (String)
  AdditionalTermBondIssuer?: string// [1] 40007 (String)
  EncodedAdditionalTermBondIssuerLen?: number// [1] 40008 (Length)
  EncodedAdditionalTermBondIssuer?: Buffer// [1] 40009 (RawData)
  AdditionalTermBondSeniority?: string// [1] 40010 (String)
  AdditionalTermBondCouponType?: number// [1] 40011 (Int)
  AdditionalTermBondCouponRate?: number// [1] 40012 (Float)
  AdditionalTermBondMaturityDate?: Date// [1] 40013 (LocalDate)
  AdditionalTermBondParValue?: number// [1] 40014 (Float)
  AdditionalTermBondCurrentTotalIssuedAmount?: number// [1] 40015 (Float)
  AdditionalTermBondCouponFrequencyPeriod?: number// [1] 40016 (Int)
  AdditionalTermBondCouponFrequencyUnit?: string// [1] 40017 (String)
  AdditionalTermBondDayCount?: number// [1] 40018 (Int)
}
