export interface IAllocCommissionDataGrp {
  AllocCommissionAmount?: number// [1] 2654 (Float)
  AllocCommissionAmountType?: number// [1] 2655 (Int)
  AllocCommissionBasis?: string// [1] 2656 (String)
  AllocCommissionCurrency?: string// [1] 2657 (String)
  AllocCommissionUnitOfMeasure?: string// [1] 2658 (String)
  AllocCommissionUnitOfMeasureCurrency?: string// [1] 2659 (String)
  AllocCommissionRate?: number// [1] 2660 (Float)
  AllocCommissionSharedIndicator?: boolean// [1] 2661 (Boolean)
  AllocCommissionAmountShared?: number// [1] 2662 (Float)
  AllocCommissionLegRefID?: string// [1] 2663 (String)
  AllocCommissionDesc?: string// [1] 2664 (String)
  EncodedAllocCommissionDescLen?: number// [1] 2665 (Length)
  EncodedAllocCommissionDesc?: Buffer// [1] 2666 (RawData)
}
