export interface ILegPaymentStreamCompoundingFloatingRate {
  LegPaymentStreamCompoundingRateIndex?: string// [1] 42427 (String)
  LegPaymentStreamCompoundingRateIndexCurvePeriod?: number// [1] 42428 (Int)
  LegPaymentStreamCompoundingRateIndexCurveUnit?: string// [1] 42429 (String)
  LegPaymentStreamCompoundingRateMultiplier?: number// [1] 42430 (Float)
  LegPaymentStreamCompoundingRateSpread?: number// [1] 42431 (Float)
  LegPaymentStreamCompoundingRateSpreadPositionType?: number// [1] 42432 (Int)
  LegPaymentStreamCompoundingRateTreatment?: number// [1] 42433 (Int)
  LegPaymentStreamCompoundingCapRate?: number// [1] 42434 (Float)
  LegPaymentStreamCompoundingCapRateBuySide?: number// [1] 42435 (Int)
  LegPaymentStreamCompoundingCapRateSellSide?: number// [1] 42436 (Int)
  LegPaymentStreamCompoundingFloorRate?: number// [1] 42437 (Float)
  LegPaymentStreamCompoundingFloorRateBuySide?: number// [1] 42438 (Int)
  LegPaymentStreamCompoundingFloorRateSellSide?: number// [1] 42439 (Int)
  LegPaymentStreamCompoundingInitialRate?: number// [1] 42440 (Float)
  LegPaymentStreamCompoundingFinalRateRoundingDirection?: string// [1] 42441 (String)
  LegPaymentStreamCompoundingFinalRatePrecision?: number// [1] 42442 (Int)
  LegPaymentStreamCompoundingAveragingMethod?: number// [1] 42443 (Int)
  LegPaymentStreamCompoundingNegativeRateTreatment?: number// [1] 42444 (Int)
}
