export interface ILegDividendAccrualFloatingRate {
  LegDividendFloatingRateIndex?: string// [1] 42312 (String)
  LegDividendFloatingRateIndexCurvePeriod?: number// [1] 42313 (Int)
  LegDividendFloatingRateIndexCurveUnit?: string// [1] 42314 (String)
  LegDividendFloatingRateMultiplier?: number// [1] 42315 (Float)
  LegDividendFloatingRateSpread?: number// [1] 42316 (Float)
  LegDividendFloatingRateSpreadPositionType?: number// [1] 42317 (Int)
  LegDividendFloatingRateTreatment?: number// [1] 42318 (Int)
  LegDividendCapRate?: number// [1] 42319 (Float)
  LegDividendCapRateBuySide?: number// [1] 42320 (Int)
  LegDividendCapRateSellSide?: number// [1] 42321 (Int)
  LegDividendFloorRate?: number// [1] 42322 (Float)
  LegDividendFloorRateBuySide?: number// [1] 42323 (Int)
  LegDividendFloorRateSellSide?: number// [1] 42324 (Int)
  LegDividendInitialRate?: number// [1] 42325 (Float)
  LegDividendFinalRateRoundingDirection?: string// [1] 42326 (String)
  LegDividendFinalRatePrecision?: number// [1] 42327 (Int)
  LegDividendAveragingMethod?: number// [1] 42328 (Int)
  LegDividendNegativeRateTreatment?: number// [1] 42329 (Int)
}
