export interface IMDStatisticParameters {
  UnderlyingReturnRateValuationDateType: number// 43073
  MDStatisticScope: number// 2457
  MDStatisticSubScope?: number// 2458
  MDStatisticScopeType?: number// 2459
  MDStatisticName?: string// 2454
  MDStatisticDesc?: string// 2455
  EncodedMDStatisticDescLen?: number// 2481
  EncodedMDStatisticDesc?: Buffer// 2482
  MarketDepth?: number// 264
  MDStatisticFrequencyPeriod?: number// 2460
  MDStatisticFrequencyUnit?: number// 2461
  MDStatisticDelayPeriod?: number// 2462
  MDStatisticDelayUnit?: number// 2463
  MDStatisticIntervalType: number// 2464
  MDStatisticIntervalTypeUnit?: string// 2465
  MDStatisticIntervalPeriod?: number// 2466
  MDStatisticIntervalUnit?: number// 2467
  MDStatisticStartDate?: Date// 2468
  MDStatisticEndDate?: Date// 2469
  MDStatisticStartTime?: Date// 2470
  MDStatisticEndTime?: Date// 2471
  MDStatisticRatioType?: number// 2472
  TradingCapacity?: number// 1815
  OrdType?: string// 40
  TimeInForce?: string// 59
  QuoteCondition?: string// 276
  TradeCondition?: string// 277
  RelativeValueSide?: number// 2532
  TradeInputSource?: string// 578
  TradingSessionID?: string// 336
  TradingSessionSubID?: string// 625
}
