export interface IPaymentStreamCompoundingFloatingRate {
  PaymentStreamCompoundingRateIndex?: string// [1] 42628 (String)
  PaymentStreamCompoundingRateIndexCurvePeriod?: number// [1] 42629 (Int)
  PaymentStreamCompoundingRateIndexCurveUnit?: string// [1] 42630 (String)
  PaymentStreamCompoundingRateMultiplier?: number// [1] 42631 (Float)
  PaymentStreamCompoundingRateSpread?: number// [1] 42632 (Float)
  PaymentStreamCompoundingRateSpreadPositionType?: number// [1] 42633 (Int)
  PaymentStreamCompoundingRateTreatment?: number// [1] 42634 (Int)
  PaymentStreamCompoundingCapRate?: number// [1] 42635 (Float)
  PaymentStreamCompoundingCapRateBuySide?: number// [1] 42636 (Int)
  PaymentStreamCompoundingCapRateSellSide?: number// [1] 42637 (Int)
  PaymentStreamCompoundingFloorRate?: number// [1] 42638 (Float)
  PaymentStreamCompoundingFloorRateBuySide?: number// [1] 42639 (Int)
  PaymentStreamCompoundingFloorRateSellSide?: number// [1] 42640 (Int)
  PaymentStreamCompoundingInitialRate?: number// [1] 42641 (Float)
  PaymentStreamCompoundingFinalRateRoundingDirection?: string// [1] 42642 (String)
  PaymentStreamCompoundingFinalRatePrecision?: number// [1] 42643 (Int)
  PaymentStreamCompoundingAveragingMethod?: number// [1] 42644 (Int)
  PaymentStreamCompoundingNegativeRateTreatment?: number// [1] 42645 (Int)
}
