export interface IUnderlyingPaymentStreamCompoundingFloatingRate {
  UnderlyingPaymentStreamCompoundingRateIndex?: string// [1] 42923 (String)
  UnderlyingPaymentStreamCompoundingRateIndexCurvePeriod?: number// [1] 42924 (Int)
  UnderlyingPaymentStreamCompoundingRateIndexCurveUnit?: string// [1] 42925 (String)
  UnderlyingPaymentStreamCompoundingRateMultiplier?: number// [1] 42926 (Float)
  UnderlyingPaymentStreamCompoundingRateSpread?: number// [1] 42927 (Float)
  UnderlyingPaymentStreamCompoundingRateSpreadPositionType?: number// [1] 42928 (Int)
  UnderlyingPaymentStreamCompoundingRateTreatment?: number// [1] 42929 (Int)
  UnderlyingPaymentStreamCompoundingCapRate?: number// [1] 42930 (Float)
  UnderlyingPaymentStreamCompoundingCapRateBuySide?: number// [1] 42931 (Int)
  UnderlyingPaymentStreamCompoundingCapRateSellSide?: number// [1] 42932 (Int)
  UnderlyingPaymentStreamCompoundingFloorRate?: number// [1] 42933 (Float)
  UnderlyingPaymentStreamCompoundingFloorRateBuySide?: number// [1] 42934 (Int)
  UnderlyingPaymentStreamCompoundingFloorRateSellSide?: number// [1] 42935 (Int)
  UnderlyingPaymentStreamCompoundingInitialRate?: number// [1] 42936 (Float)
  UnderlyingPaymentStreamCompoundingFinalRateRoundingDirection?: string// [1] 42937 (String)
  UnderlyingPaymentStreamCompoundingFinalRatePrecision?: number// [1] 42938 (Int)
  UnderlyingPaymentStreamCompoundingAveragingMethod?: number// [1] 42939 (Int)
  UnderlyingPaymentStreamCompoundingNegativeRateTreatment?: number// [1] 42940 (Int)
}
