import { IUnderlyingPaymentStreamNonDeliverableFixingDatesBusinessCenterGrp } from './underlying_payment_stream_non_deliverable_fixing_dates_business_center_grp'
import { IUnderlyingPaymentStreamNonDeliverableSettlRateSource } from './underlying_payment_stream_non_deliverable_settl_rate_source'
import { IUnderlyingPaymentStreamNonDeliverableFixingDateGrp } from './underlying_payment_stream_non_deliverable_fixing_date_grp'
import { IUnderlyingSettlRateDisruptionFallbackGrp } from './underlying_settl_rate_disruption_fallback_grp'

export interface IUnderlyingPaymentStreamNonDeliverableSettlTerms {
  UnderlyingPaymentStreamNonDeliverableRefCurrency?: string// 40648
  UnderlyingPaymentStreamNonDeliverableFixingDatesBusinessDayConvention?: number// 40649
  UnderlyingPaymentStreamNonDeliverableFixingDatesRelativeTo?: number// 40651
  UnderlyingPaymentStreamNonDeliverableFixingDatesOffsetPeriod?: number// 40652
  UnderlyingPaymentStreamNonDeliverableFixingDatesOffsetUnit?: string// 40653
  UnderlyingPaymentStreamNonDeliverableFixingDatesOffsetDayType?: number// 40654
  UnderlyingPaymentStreamNonDeliverableFixingDatesBusinessCenterGrp?: IUnderlyingPaymentStreamNonDeliverableFixingDatesBusinessCenterGrp[]
  UnderlyingPaymentStreamNonDeliverableSettlRateSource?: IUnderlyingPaymentStreamNonDeliverableSettlRateSource
  UnderlyingPaymentStreamNonDeliverableFixingDateGrp?: IUnderlyingPaymentStreamNonDeliverableFixingDateGrp
  UnderlyingSettlRateDisruptionFallbackGrp?: IUnderlyingSettlRateDisruptionFallbackGrp[]
}
