import { IUnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenterGrp } from './underlying_provision_option_relevant_underlying_date_business_center_grp'

export interface IUnderlyingProvisionOptionRelevantUnderlyingDate {
  UnderlyingProvisionOptionRelevantUnderlyingDateUnadjusted?: Date// 42142
  UnderlyingProvisionOptionRelevantUnderlyingDateBusinessDayConvention?: number// 42143
  UnderlyingProvisionOptionRelevantUnderlyingDateRelativeTo?: number// 42144
  UnderlyingProvisionOptionRelevantUnderlyingDateOffsetPeriod?: number// 42145
  UnderlyingProvisionOptionRelevantUnderlyingDateOffsetUnit?: string// 42146
  UnderlyingProvisionOptionRelevantUnderlyingDateOffsetDayType?: number// 42147
  UnderlyingProvisionOptionRelevantUnderlyingDateAdjusted?: Date// 42148
  UnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenterGrp?: IUnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenterGrp[]
}
