export interface IUnderlyingAdditionalTermBondRefGrp {
  UnderlyingAdditionalTermBondSecurityID?: string// [1] 41341 (String)
  SecurityIDSource?: string// [1] 22 (String)
  UnderlyingAdditionalTermBondDesc?: string// [1] 41709 (String)
  EncodedUnderlyingAdditionalTermBondDescLen?: number// [1] 41710 (Length)
  EncodedUnderlyingAdditionalTermBondDesc?: Buffer// [1] 41711 (RawData)
  UnderlyingAdditionalTermBondCurrency?: string// [1] 41712 (String)
  UnderlyingAdditionalTermBondIssuer?: string// [1] 42017 (String)
  EncodedUnderlyingAdditionalTermBondIssuerLen?: number// [1] 42025 (Length)
  EncodedUnderlyingAdditionalTermBondIssuer?: Buffer// [1] 42026 (RawData)
  UnderlyingAdditionalTermBondSeniority?: string// [1] 42027 (String)
  UnderlyingAdditionalTermBondCouponType?: number// [1] 42028 (Int)
  UnderlyingAdditionalTermBondCouponRate?: number// [1] 42029 (Float)
  UnderlyingAdditionalTermBondMaturityDate?: Date// [1] 42030 (LocalDate)
  UnderlyingAdditionalTermBondParValue?: number// [1] 42031 (Float)
  UnderlyingAdditionalTermBondCurrentTotalIssuedAmount?: number// [1] 42032 (Float)
  UnderlyingAdditionalTermBondCouponFrequencyPeriod?: number// [1] 42033 (Int)
  UnderlyingAdditionalTermBondCouponFrequencyUnit?: string// [1] 42034 (String)
  AdditionalTermBondDayCount?: number// [1] 40018 (Int)
}
